export const filterScriptOptions = [
  "",
  "item.meta['value']; // メモ欄に<value>の記述がある",
  "item.name.match('value'); // 名前にvalueを含む",
  "item.id > v(10); // IDが変数[10]の値より大きい",
  "s(parseInt(item.meta['value'])); // <value:n>のスイッチがON",
  "item !== ''; // 空文字以外",
  "!!item; // null, undefined, 0, 空文字以外",
  "item.stypeId === v(10); // スキルタイプが変数[10]の値と等しい",
  "item.etypeId === v(10); // 装備タイプが変数[10]の値と等しい",
  "item.wtypeId === v(10); // 武器タイプが変数[10]の値と等しい",
  "item.atypeId === v(10); // 防具タイプが変数[10]の値と等しい",
  "item.itypeId === 1; // アイテムタイプが[通常アイテム]",
  "this._actor.canEquip(item); // メインメニューで選択したアクターが装備可能",
  "this._actor.canUse(item); // メインメニューで選択したアクターが使用可能",
];
export const isEnableScriptOptioins = [
  "",
  "item.meta['value']; // メモ欄に<value>の記述がある",
  "item.name.match('value'); // 名前にvalueを含む",
  "item.id > v(10); // IDが変数[10]の値より大きい",
  "s(parseInt(item.meta['value'])); // <value:n>のスイッチがON",
  "item !== ''; // 空文字以外",
  "!!item; // null, undefined, 0, 空文字以外",
  "item.stypeId === v(10); // スキルタイプが変数[10]の値と等しい",
  "item.etypeId === v(10); // 装備タイプが変数[10]の値と等しい",
  "item.wtypeId === v(10); // 武器タイプが変数[10]の値と等しい",
  "item.atypeId === v(10); // 防具タイプが変数[10]の値と等しい",
  "item.itypeId === 1; // アイテムタイプが[通常アイテム]",
  "this._actor.canEquip(item); // メインメニューで選択したアクターが装備可能",
  "this._actor.canUse(item); // メインメニューで選択したアクターが使用可能",
];
export const sortScriptOptions = [
  "",
  "a.id - b.id; // ID順",
  "a.name.localeCompare(b.name); // 名前順",
  "this.intMeta(a,'order') - this.intMeta(b,'order'); // メモ欄のorder順",
  "a.price - b.price; // 値段順",
  "a.params[0] - b.params[0]; // HP順",
  "a.params[1] - b.params[1]; // MP順",
  "a.params[2] - b.params[2]; // 攻撃力順",
  "a.params[3] - b.params[3]; // 防御力順",
  "a.params[4] - b.params[4]; // 魔法力順",
  "a.params[5] - b.params[5]; // 魔法防御順",
  "a.params[6] - b.params[6]; // 敏捷性順",
  "a.params[7] - b.params[7]; // 運順",
];

export const mappingScriptOptions = [
  "",
  "item.actor(); // Game_ActorからデータベースのActorに変換",
  "$dataSkills[item.skillId]; // 習得スキル情報をデータベースのSkillに変換",
  "$dataSystem.equipTypes[item]; // 装備スロットIDを装備スロット名称に変換",
];

export const eventScriptOptions = [
  "SceneManager.callCustomMenu('Scene___'); // 別のカスタムメニューに移動",
  "this.popScene(); // 元のシーンに戻る",
  "SceneManager.goto(Scene_Map); // マップ画面に遷移",
  "SceneManager.changeWindowFocus('window1'); // 指定ウィンドウにフォーカス",
  "SceneManager.changeWindowIndex('window1', 1); // 指定ウィンドウのインデックス変更",
  "SceneManager.trashScene(); // 元のシーン情報を破棄する",
  "SceneManager.showMapPicture(1, '', 0, 0, 0, 100, 100, 255, 1); // マップ画面にピクチャを表示",
  "this.executeSave( SceneManager.findCustomMenuWindow(this._activeWindowId)._index); //セーブ実行",
  "this.executeLoad ( SceneManager.findCustomMenuWindow(this._activeWindowId)._index); //ロード実行",
  // uy
  "$gameMessage.add('メッセージを表示します'); //メッセージを表示",
  // "$gameTemp.reserveCommonEvent(コモンイベントID); //コモンイベントを実行",
  "var w = SceneManager.findCustomMenuWindow(this._activeWindowId);var item = w._list[w._index];console.log(item) // アイテムを取得",
];

export const listScriptOptions = [
  "null; // なし(単項目表示ウインドウ用)",
  "$gameParty.members(); // パーティメンバー",
  "$gameParty.battleMembers(); // 戦闘メンバー",
  "$gameParty.reserveMembers(); // リザーブメンバー",
  "$gameParty.items(); // 所持消耗品",
  "$gameParty.weapons(); // 所持武器",
  "$gameParty.armors(); // 所持防具",
  "$gameParty.equipItems(); // 所持装備品",
  "$gameParty.allItems(); // 所持アイテム",
  "[this._actor]; // メインメニューで選択したアクター",
  "this._actor.weapons(); // メインメニューで選択したアクターの装備武器",
  "$gameParty.members()[v(1)].weapons(); // 変数[1]のPTメンバーの装備武器",
  "this.createSaveFiles(); // セーブファイル一覧",
  "this._actor.armors(); // メインメニューで選択したアクターの装備防具",
  "this._actor.equips(); // メインメニューで選択したアクターの装備品",
  "this._actor.equipSlots(); // メインメニューで選択したアクターの装備スロットID",
  "this._actor.skills(); // メインメニューで選択したアクターの所持スキル",
  "this._actor.usableSkills(); // メインメニューで選択したアクターの使用可能スキル",
  "this._actor.currentClass().learnings; //メインメニューで選択したアクターの職業の習得スキル",
  "$dataActors.filter(data => !!data); // データベースのアクター",
  "$dataClasses.filter(data => !!data); // データベースの職業",
  "$dataSkills.filter(data => !!data); // データベースのスキル",
  "$dataItems.filter(data => !!data); // データベースのアイテム",
  "$dataWeapons.filter(data => !!data); // データベースの武器",
  "$dataArmors.filter(data => !!data); // データベースの防具",
  "$dataEnemies.filter(data => !!data); // データベースの敵キャラ",
  "$dataTroops.filter(data => !!data); // データベースの敵グループ",
  "$dataStates.filter(data => !!data); // データベースのステート",
  "$dataItems.concat($dataWeapons, $dataArmors).filter(data => !!data); // アイテム、武器防具",
  "$dataSystem.weaponTypes.filter((d, i) => i > 0); // 武器タイプ",
  "$dataSystem.armorTypes.filter((d, i) => i > 0); // 防具タイプ",
  "$dataSystem.skillTypes.filter((d, i) => i > 0); // スキルタイプ",
  "$dataSystem.equipTypes.filter((d, i) => i > 0); // 装備タイプ",
  "$dataSystem.elements.filter((d, i) => i > 0); // 属性",
  "$dataSystem.switches; // スイッチ名",
  "$dataSystem.variables; // 変数名",
  "$dataSystem.params; // 能力値(用語)",
  "$dataSystem.commands; // コマンド(用語)",
  "$dataSystem.basic; // 基本ステータス(用語)",
];

export const drawItemoptions = [
  "this.drawIcon(item.iconIndex, r.x, r.y, r.width); // アイコン",
  "this.drawFace(item.faceName(), item.faceIndex(), r.x, r.y); // フェイスグラフィック",
  "this.drawCharacter(item.characterName(), item.characterIndex(), r.x, r.y); // キャラクター",
  "this.drawActorCharacter(item, r.x + 24, r.y + 48); // アクターキャラクター",
  "this.drawActorCharacter(this._actor, r.x, r.y); // メインメニューで選択したアクターキャラクター",
  "this.drawActorFace(item, r.x, r.y); // アクターフェイス",
  "this.drawActorName(item, r.x, r.y); // アクター名称",
  "this.drawActorClass(item, r.x, r.y); // アクター職業",
  "this.drawActorNickname(item, r.x, r.y); // アクターのニつ名",
  "this.drawActorLevel(item, r.x, r.y); // アクターのレベル",
  "this.drawActorIcons(item, r.x, r.y); // アクターのステートアイコン",
  "this.drawActorSimpleStatus(item, r.x, r.y, r.width); // アクターのステータス",
  "this.drawEnemy(r.x, r.y, 'center', 'bottom'); // 敵キャラの画像",
  "this.drawParam(0, r.x, r.y, 'right'); // DBパラメータ(0:HP 1:MP...)",
  "this.drawItemName(item, r.x, r.y, r.width); // アイテム、スキルの名称(アイコン含む)",
  "this.drawText($gameParty.numItems(item), r.x, r.y, r.width, 'right'); // アイテムの所持数",
  "this.drawTextEx(`Text:${item.name}`, r.x, r.y, r.width); // 任意のテキスト描画(制御文字変換あり)",
  "this.drawText(`Text:${item.name}`, r.x, r.y, r.width, 'right'); // 任意のテキスト描画(制御文字変換なし)",
  "this.changeTextColor(ColorManager.textColor(1)); // テキストカラー変更(drawTextでのみ有効)",
  "this.drawText(this.findWindowItem('window1').name, r.x, r.y, r.width); // 別ウインドウで選択しているアイテム名",
  "this.drawNotePicture('noteValue', r.x, r.y, 'left', 0, 0, 1.0, 1.0); // 指定したメモ欄のピクチャ",
  "this.drawPicture('Actor1_1', r.x, r.y, 'left', 'top', 1, 1); // ピクチャを描画",
  "this.placeActorName(item, r.x, r.y); // アクター名称(戦闘用)",
  "this.placeStateIcon(item, r.x, r.y); // ステートアイコン(戦闘用)",
  "this.placeGauge(item, 'hp', r.x, r.y); // HPゲージ(戦闘用)",
  "this.placeBasicGauges(item, r.x, r.y); // ゲージセット(戦闘用)",
  "this.drawNoteText('noteValue', r.x, r.y); // 指定したメモ欄の内容を描画",
  "this.drawNoteText('noteValue', r.x, r.y, 'right'); // メモ欄の内容を右寄せ描画",
  "this.drawSavefileInfo(item, r.x, r.y, r.width); // セーブファイルの内容を描画",
];
